[package]
name = "jmeter-to-goose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
quick-xml = { version = "0.27.1", features = ["serde-types", "serialize"] }
serde = "1.0.154"